project_id = "duktrvqfbvpfajuajhci"

[functions.lupp-widget-bootstrap]
verify_jwt = false

[functions.nuvemshop-oauth-callback]
verify_jwt = false

[functions.shopify-oauth-callback]
verify_jwt = false

[functions.nuvemshop-lgpd-webhooks]
verify_jwt = false

[functions.shopify-compliance-webhooks]
verify_jwt = false

[functions.shopify-session-token-ping]
verify_jwt = false

[functions.shopify-embedded-session]
verify_jwt = false

[functions.shopify-app-config]
verify_jwt = false

[functions.shopify-connect-custom-app]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-cancel-subscription]
verify_jwt = true

[functions.lupp-change-trial-plan]
verify_jwt = true
