name = "Luup"
client_id = "422735bb080ecf76ae0d49bc415df1e3"
application_url = "https://www.playluup.com.br"
embedded = true

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "read_products,read_inventory,read_locations"

[auth]
redirect_urls = [
  "https://duktrvqfbvpfajuajhci.supabase.co/functions/v1/shopify-oauth-callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "https://duktrvqfbvpfajuajhci.supabase.co/functions/v1/shopify-compliance-webhooks"