import { env } from "@/env";
import { asaasApiBase, BaseClient, readAsaasError, toQueryString } from "./base";

/** Subscriptions resource: recurring charges (create/update/cancel/list). */
export class SubscriptionsClient extends BaseClient {
  get endpoint() {
    return `${this.apiBase}/subscriptions`;
  }

  async create(payload: Record<string, unknown>) {
    return this.doRequest("POST", this.endpoint, payload);
  }

  async list(params: Record<string, string | number | undefined> = {}) {
    return this.doRequest("GET", `${this.endpoint}${toQueryString(params)}`);
  }

  /** Charges generated by one subscription. */
  async payments(subscriptionId: string) {
    return this.doRequest("GET", `${this.endpoint}/${subscriptionId}/payments`);
  }

  async update(subscriptionId: string, payload: Record<string, unknown>) {
    return this.doRequest("PUT", `${this.endpoint}/${subscriptionId}`, payload);
  }

  async remove(subscriptionId: string) {
    return this.doRequest("DELETE", `${this.endpoint}/${subscriptionId}`);
  }
}

/**
 * Legacy flat helper (cancel-subscription route): throws
 * Error(<asaas error message>) on non-2xx, like the original edge function.
 */
export async function deleteAsaasSubscription(providerSubscriptionId: string) {
  const response = await fetch(
    `${asaasApiBase()}/subscriptions/${providerSubscriptionId}`,
    {
      headers: { access_token: env.ASAAS_API_KEY ?? "" },
      method: "DELETE",
    },
  );

  if (!response.ok) {
    throw new Error(await readAsaasError(response));
  }

  return (await response.json().catch(() => ({}))) as Record<string, unknown>;
}
